### ISSUE TITLE
Adding new metric

### ISSUE THREAD

**Issue by zuliandres** [DIVERSIFY-project/amiunique#51]
Hello, 
I have an idea for a new metric. Unfortunately, I have little experience with this framework. I wanted to know if I want to collect a new feature and add it to the application and DB, could you give me some pointers on how to edit the application's code?
Regards and cheers for great work!

**Comment by plaperdr** [comment]
Hi zuliandres,
Thanks for your interest in the project! 
We are planning an update to the website in the coming months where adding new features will be much easier. 
In the meantime, if you want to do it on the current version, you can add your code [here](https://github.com/DIVERSIFY-project/amiunique/blob/master/website/app/views/fp.scala.html) and add the JavaScript code associated with it on the same page (or you could add your attribute in the main FP JS script [here](https://github.com/DIVERSIFY-project/amiunique/blob/master/website/public/javascripts/fp.js)). Then, you have to add the new attribute in the SQL database and update the model associated with it in the app [here](https://github.com/DIVERSIFY-project/amiunique/blob/master/website/app/models/FpDataEntityManager.java) and [here](https://github.com/DIVERSIFY-project/amiunique/blob/master/website/app/models/FpDataEntity.java).

**Comment by zuliandres** [comment]
Thanks a lot, I will try it today!

**Comment by zuliandres** [comment]
Hey @plaperdr,

I am almost done with the integration it appears... however I'm not sure why I am getting this error when trying to get my own fingerprint. Maybe you can look it over? 


```
[error] o.h.e.j.s.SqlExceptionHelper - Data truncation: Data too long for column 'octaneScore' at row 1
[error] play - Cannot invoke the action, eventually got an error: java.lang.RuntimeException: javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute statement
[error] application -

! @79b7ipbk0 - Internal server error, for (POST) [/results] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute statement]]
        at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:146) [scala-library-2.11.6.jar:na]
Caused by: java.lang.RuntimeException: javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute statement
        at models.FpDataEntityManager.withTransaction(FpDataEntityManager.java:24) ~[na:na]
        at models.FpDataEntityManager.createFull(FpDataEntityManager.java:108) ~[na:na]
        at controllers.FPController.addFingerprint(FPController.java:217) ~[na:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$16$$anonfun$apply$16.apply(routes_routing.scala:320) ~[na:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$16$$anonfun$apply$16.apply(routes_routing.scala:320) ~[na:na]
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute statement
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763) ~[hibernate-entitymanager-4.3.6.Final.jar:4.3.6.Final]
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677) ~[hibernate-entitymanager-4.3.6.Final.jar:4.3.6.Final]
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1683) ~[hibernate-entitymanager-4.3.6.Final.jar:4.3.6.Final]
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1187) ~[hibernate-entitymanager-4.3.6.Final.jar:4.3.6.Final]
        at models.FpDataEntityManager.lambda$createFull$7(FpDataEntityManager.java:145) ~[na:na]
Caused by: org.hibernate.exception.DataException: could not execute statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:69) ~[hibernate-core-4.3.6.Final.jar:4.3.6.Final]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49) ~[hibernate-core-4.3.6.Final.jar:4.3.6.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126) ~[hibernate-core-4.3.6.Final.jar:4.3.6.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112) ~[hibernate-core-4.3.6.Final.jar:4.3.6.Final]
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211) ~[hibernate-core-4.3.6.Final.jar:4.3.6.Final]
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'octaneScore' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3885) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
```

Regards and Thanks a bunch!

**Comment by zuliandres** [comment]
Ok I was able to resolve on my own thanks! The problem was the ordering of the metrics on FPController.java file. 

Regards!
